FROM adoptopenjdk/openjdk11:alpine-jre

RUN mkdir /deployments

EXPOSE 8080
ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"

COPY maven/lib/* /deployments/lib/
COPY maven/*-runner.jar /deployments/app.jar

CMD java $JAVA_OPTS -jar /deployments/app.jar
